import React from 'react'
import { GetStaticProps, GetStaticPropsResult } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getClient, overlayDrafts } from 'lib/sanity.server'
import { indexQuery } from 'lib/queries'
import ProjectType from 'types/project'

type Props = {
  allProjects: ProjectType[]
  preview: boolean
}

const Index: React.FunctionComponent<Props> = ({ allProjects, preview }: Props) => {
  console.log(allProjects)

  return (
    <div className="h-screen min-h-screen flex justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="w-[333px] h-[111px] bg-[#0000ff] flex items-center justify-center">
          <span className="text-[22px] text-gray-100">Tailwind JIT Component</span>
        </div>
        {allProjects.map((p) => {
          return (
            <div key={p._id}>
              <h2>{p.title.en}</h2>
            </div>
          )
        })}
      </main>
    </div>
  )
}

export default Index

type Params = {
  allProjects: ProjectType[]
  preview: boolean
}

export const getStaticProps: GetStaticProps = async ({
  preview = false,
}): Promise<GetStaticPropsResult<Params>> => {
  const allProjects = overlayDrafts(await getClient(preview).fetch(indexQuery))
  return {
    props: { allProjects, preview },
  }
}
